default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 123 } %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_idox_development

test:
  <<: *default
  database: app_idox_test

production:
  <<: *default
  database: app_idox_production
  username: app_idox
  password: <%= ENV['APP_IDOX_DATABASE_PASSWORD'] %>
